nmklotas/GitLabApiClient

src/GitLabApiClient/Models/Issues/Requests/CreateIssueRequest.cs, src/GitLabApiClient/Models/Issues/Requests/UpdateIssueRequest.cs, src/GitLabApiClient/Models/Issues/Responses/Issue.cs, src/GitLabApiClient/Models/Issues/Responses/IssueTimeStatistic.cs, test/GitLabApiClient.Test/IssuesClientTest.cs
Adding missing properties (weight and time stats) in the response model of the gitlab issue client #12
=> Add missing issue weight and issue time statistics

test/GitLabApiClient.Test/ReleasesTest.cs
On my previous PR I forgot to make the class ReleasesTest class public, so the tests would not have been run.
Sry, my fault - pease merge :)
=> Enabled tests for feature/branches

src/GitLabApiClient/TagClient.cs, test/GitLabApiClient.Test/TagsClientTest.cs
Fixes a problem with TagClient->GetAsync
=>  BUG FIX: repository keyword was missing in the request url for TagClient->GetAsync

src/GitLabApiClient/GitLabApiClient.csproj
4.5 was end of life as of 2016-01-12
a modest bump but I'd suggest going higher 😅
=> target .NET Framework 4.5.2

src/GitLabApiClient/Models/Projects/Requests/CreateProjectLabelRequest.cs, src/GitLabApiClient/Models/Projects/Requests/UpdateProjectLabelRequest.cs
These were saved in windows-1252 😓 the characters that had their encoding changes was `‘` and `’`
=> fix files encoding to UTF 8

src/GitLabApiClient/Internal/Queries/ProjectMergeRequestsQueryBuilder.cs, src/GitLabApiClient/MergeRequestsClient.cs, src/GitLabApiClient/Models/MergeRequests/Requests/ProjectMergeRequestsQueryOptions.cs, test/GitLabApiClient.Test/Internal/Queries/ProjectMergeRequestsQueryBuilderTest.cs
https://gitlab.com/api/v4/merge_requests?id=3 ignores id and returns all your open merge requests
https://docs.gitlab.com/ee/api/merge_requests.html
=> fix Merge Request API, id is a path param not a query param

src/GitLabApiClient/Internal/Queries/ReleaseQueryBuilder.cs, src/GitLabApiClient/Models/Releases/Requests/ReleaseQueryOptions.cs, src/GitLabApiClient/ReleaseClient.cs, test/GitLabApiClient.Test/ReleasesTest.cs
Seems like someone added the path parameters to the query builder, which seems wrong.
https://docs.gitlab.com/ee/api/releases/#list-releases
=> Release API has no query paramaters

src/GitLabApiClient/Internal/Queries/TagQueryBuilder.cs, src/GitLabApiClient/Models/Tags/Requests/TagQueryOptions.cs, src/GitLabApiClient/TagClient.cs
I agree that GitLab API docs can be confusing 😅 However id param is a path param as shown in the URL example: `GET /projects/:id/repository/tags`
https://docs.gitlab.com/ee/api/tags/#list-tags
=> fix Tags API does not have a id query param, id is a path param

src/GitLabApiClient/Models/Projects/Requests/TransferProjectRequest.cs, src/GitLabApiClient/ProjectsClient.cs
similar to https://github.com/jdalrymple/node-gitlab/pull/145
Added in 11.1:
docs.gitlab.com/ee/api/projects.html#transfer-a-project-to-a-new-namespace
about.gitlab.com/2018/07/22/gitlab-11-1-released/#transfer-projects-between-namespaces-via-api
The new thing is that you can transfer a project to another user or another group while the group api only allows to move to a group
=> add transfer project namespace

src/GitLabApiClient/BranchClient.cs, src/GitLabApiClient/Internal/Queries/BranchQueryBuilder.cs, src/GitLabApiClient/Models/Branches/Requests/BranchQueryOptions.cs
fixed up URLs, `projects/{projectId}/branches` returns 404
branch query parameters only have a `search` option
https://docs.gitlab.com/ee/api/branches.html
=> fix branch client url and query params

src/GitLabApiClient/Internal/Http/GitLabApiPagedRequestor.cs, test/GitLabApiClient.Test/Internal/Http/HttpResponseHeadersExtensionsTest.cs
Fixes an error, if a header key is present, but has no (empty) value. Fixes exception for `X-Next-Page` and `X-Prev-Page`.
=> #74: Fix for empty (not null) header values

src/GitLabApiClient/CommitsClient.cs, src/GitLabApiClient/GitLabClient.cs, src/GitLabApiClient/Internal/Queries/CommitRefsQueryBuilder.cs, src/GitLabApiClient/Models/Commits/Requests/CommitRefsQueryOptions.cs, src/GitLabApiClient/Models/Commits/Responses/CommitRef.cs, src/GitLabApiClient/Models/Commits/Responses/CommitRefType.cs, test/GitLabApiClient.Test/CommitsClientTest.cs, test/GitLabApiClient.Test/Internal/Queries/CommitRefsQueryBuilderTest.cs
=> #76 Implementation for commit refs

.travis.yml, src/GitLabApiClient/GitLabApiClient.csproj
With the addition of GitVersion we do not need to specify version in csproj.
RepositoryType defaults to git.
=> Remove unused csproj properties

src/GitLabApiClient/GitLabClient.cs, src/GitLabApiClient/Models/Webhooks/Requests/CreateWebhookRequest.cs, src/GitLabApiClient/Models/Webhooks/Responses/Webhook.cs, src/GitLabApiClient/WebhookClient.cs
The following operations have been implemented:
1. create
2. delete
3. get all
4. get by ID
=> Basic operations to work with webhooks

src/GitLabApiClient/Models/Releases/Requests/CreateReleaseRequest.cs
As documented here:
https://docs.gitlab.com/ee/api/releases/#create-a-release
When creating a GitLab release, there is additional property called `Ref` which is used when the Tag that the Release is targeting doesn't exist yet.  This Ref can be a SHA for a commit, another tag, or a branch name.  In the testing that I have done, the tag_name property is still required, so I don't think we need to create any additional constructors, only have the ability to set the `Ref` property when required.
Fixes #96
=> (GH-96) Add Ref property to CreateReleaseRequest

src/GitLabApiClient/GitLabClient.cs, src/GitLabApiClient/Internal/Http/GitLabHttpFacade.cs, src/GitLabApiClient/Models/Oauth/Requests/AccessTokenRequest.cs, src/GitLabApiClient/Models/Oauth/Responses/AccessTokenResponse.cs, test/GitLabApiClient.Test/GitLabClientTest.cs, test/GitLabApiClient.Test/Utilities/GitLabApiHelper.cs
=> add support for OAuth authorization

src/GitLabApiClient/CommitsClient.cs, src/GitLabApiClient/Models/Commits/Responses/Diff.cs, test/GitLabApiClient.Test/CommitsClientTest.cs
Adds support for the projects/:id/repository/commits/:sha/diff endpoint and the associated return type.
=> add support for retrieving the diffs from a commit

src/GitLabApiClient/Internal/Queries/IssuesQueryBuilder.cs, src/GitLabApiClient/Models/Issues/Requests/IssuesQueryOptions.cs, src/GitLabApiClient/Models/Issues/Responses/Issue.cs, src/GitLabApiClient/Models/Issues/Responses/IssueTaskCompletionStatus.cs, test/GitLabApiClient.Test/Internal/Queries/IssuesQueryBuilderTest.cs, test/GitLabApiClient.Test/IssuesClientTest.cs
Implementation for issue #120 
- add Task status in issue model
- add author username and assignee username filter
=> Extend issue with task status info

src/GitLabApiClient/Models/Commits/Responses/Commit.cs
Issues, Merge Requests and Milestones expose a `WebUrl` property that contains the link to the GitLab web interface for the item.
The `Commit` class does not have such a property, but the server response includes it (according to the [GitLab API docs](https://docs.gitlab.com/ee/api/commits.html))
This PR adds the `WebUrl` property to the `Commit` class as well.
The PR also adds a `global.json` to pin the .NET Core SDK version to 3.1.100 because the build seems to be broken on the recently released SDK 3.1.200 (https://github.com/dotnet/sdk/issues/10878)
=> Add WebUrl property to Commit

src/GitLabApiClient/ConnectionClient.cs, src/GitLabApiClient/GitLabClient.cs, src/GitLabApiClient/Internal/Http/GitLabHttpFacade.cs
Done in the "spirit" of ConnectionClient in Octokit, see https://github.com/octokit/octokit.net/blob/master/Octokit/Http/IConnection.cs
Needed for APIs that are not yet implemented, or a tough to implement in an sdk appropriate way, such as https://docs.gitlab.com/ee/api/merge_requests.html#list-issues-that-will-close-on-merge
Closes #112
=> Added ConnectionClient

src/GitLabApiClient/Internal/Queries/BranchQueryBuilder.cs, src/GitLabApiClient/Internal/Queries/CommitQueryBuilder.cs, src/GitLabApiClient/Internal/Queries/CommitRefsQueryBuilder.cs, src/GitLabApiClient/Internal/Queries/CommitStatusesQueryBuilder.cs, src/GitLabApiClient/Internal/Queries/GroupLabelsQueryBuilder.cs, src/GitLabApiClient/Internal/Queries/GroupsProjectsQueryBuilder.cs, src/GitLabApiClient/Internal/Queries/GroupsQueryBuilder.cs, src/GitLabApiClient/Internal/Queries/IssuesQueryBuilder.cs, src/GitLabApiClient/Internal/Queries/JobQueryBuilder.cs, src/GitLabApiClient/Internal/Queries/MergeRequestsQueryBuilder.cs, src/GitLabApiClient/Internal/Queries/MilestonesQueryBuilder.cs, src/GitLabApiClient/Internal/Queries/PipelineQueryBuilder.cs, src/GitLabApiClient/Internal/Queries/ProjectIssueNotesQueryBuilder.cs, src/GitLabApiClient/Internal/Queries/ProjectMergeRequestsNotesQueryBuilder.cs, src/GitLabApiClient/Internal/Queries/ProjectMergeRequestsQueryBuilder.cs, src/GitLabApiClient/Internal/Queries/ProjectsQueryBuilder.cs, src/GitLabApiClient/Internal/Queries/QueryBuilder.cs, src/GitLabApiClient/Internal/Queries/ReleaseQueryBuilder.cs, src/GitLabApiClient/Internal/Queries/TagQueryBuilder.cs, src/GitLabApiClient/Internal/Queries/ToDoListQueryBuilder.cs, src/GitLabApiClient/Internal/Queries/TreeQueryBuilder.cs, src/GitLabApiClient/PipelineClient.cs, test/GitLabApiClient.Test/Internal/Queries/PipelineQueryBuilderTest.cs
Hi,
At `thetradedesk` we have been using a fork of this project for over a year now, and one of the foundational changes we made was to introduce thread safety to the query builders in the API client. We found that this was the only part of the code base that wasn't compatible with concurrent callers of the same client.
There are 2 new object allocations per request (a new NameValueCollection, and the wrapping Query object). This change makes the singleton querybuilders thread safe, as each request gets it own query object.
Please let me know any thoughts. Since the development of this library has picked up in the past 12 months, we hope to slowly contribute out changes back upstream, for the benefit of all, and so that we do not need to maintain our own fork.
fixes #104
=> Make querybuilder thread safe

src/GitLabApiClient/GroupsClient.cs, src/GitLabApiClient/Models/Groups/Requests/CreateGroupVariableRequest.cs, src/GitLabApiClient/Models/Groups/Requests/UpdateGroupVariableRequest.cs, src/GitLabApiClient/Models/Groups/Responses/Variable.cs, src/GitLabApiClient/ProjectsClient.cs, test/GitLabApiClient.Test/GitLabClientTest.cs, test/GitLabApiClient.Test/GroupsClientTest.cs, test/GitLabApiClient.Test/Utilities/GitLabContainerFixture.cs
This PR adds support for interacting with group-level variables.
I wasn't sure whether I should add the group variable types to the Variables folder or stick them into the Groups folder, so I opted for the latter. But I'm happy to move them to the Variables folder if that has preference. If so, I suggest that we rename `Variable` to `ProjectVariable` to make a clear distinction between the two types of variables, and propagate this change wherever applicable. I'm also happy to move the stuff from Variables into the Projects folder.
Either way, it will be more consistent. Just say the word.
=> Add Group Variables CRUD methods

src/GitLabApiClient/IssuesClient.cs, src/GitLabApiClient/MergeRequestsClient.cs, src/GitLabApiClient/Models/AwardEmojis/Responses/AwardEmoji.cs, src/GitLabApiClient/Models/AwardEmojis/Responses/AwardableType.cs, src/GitLabApiClient/Models/Discussions/Responses/Discussion.cs
Added GetDiscussionsAsync and GetAwardEmojisAsync methods to MergeRequestsClient, that correspond to [List project merge request discussion items](https://docs.gitlab.com/ee/api/discussions.html#list-project-merge-request-discussion-items) and [List an awardable’s award emoji](https://docs.gitlab.com/ee/api/award_emoji.html#list-an-awardables-award-emoji) api endpoints.
Added AwardEmoji, Discussion models, AwardableType enum.
Fixed typo in IssuesClient.GetNotesAsync returns documentation tag.
=> Add opportunity to retrieve merge request discussions and award emojis.

src/GitLabApiClient/Internal/Http/GitLabHttpFacade.cs
Removes thread safety but I cannot figure out why it was added in the first place.
Unless someone is running some highly parallel against the client it would be an issue.
fixes #134
=> No need for thread safety in most cases.

src/GitLabApiClient/Internal/Queries/ProjectsQueryBuilder.cs, src/GitLabApiClient/Models/Projects/Requests/ProjectQueryOptions.cs
Gitlab introduced last_activity_after and last_activitybefore filters in Project Api in 12.10 release. necessary changes has been done in ProjectQueryBuilder and ProjectQuery Options classes
=> Implement last_activity_after and last_activity_before filters in Project

src/GitLabApiClient/Models/Users/Requests/CreateUserRequest.cs
Added an option to force a random password when creating a new user in GitLab
=> Add option to force random password option when creating new user

src/GitLabApiClient/Models/MergeRequests/Responses/MergeStatus.cs
Fix issue #118 by adding the missing enum member to the `MergeStatus` enum.
=> Add missing enum member `checking` to the MergeStatus.cs

src/GitLabApiClient/Models/MergeRequests/Responses/MergeRequest.cs, test/GitLabApiClient.Test/MergeRequestClientTest.cs
Include Merge By from Merge Request Response json returned by Gitlab.
=> Processes Merged By Object from Merge Request Response

src/GitLabApiClient/Models/MergeRequests/Responses/MergeStatus.cs
This change adds support for the missing `MergeStatus` => `cannot_be_merged_recheck`.
This resolves:
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Error converting value "cannot_be_merged_recheck" to type 'GitLabApiClient.Models.MergeRequests.Responses.MergeStatus'. Path '[0].merge_status', line 1, position 5331.)
---> Newtonsoft.Json.JsonSerializationException: Error converting value "cannot_be_merged_recheck" to type 'GitLabApiClient.Models.MergeRequests.Responses.MergeStatus'. Path '[0].merge_status', line 1, position 5331.
---> System.ArgumentException: Requested value 'cannot_be_merged_recheck' was not found.
at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
at …
```
=> Add missing MergeStatus enum member for, cannot_be_merged_recheck.

src/GitLabApiClient/Internal/Http/GitLabHttpFacade.cs
GitLab allows users of an instance to specify a token prefix since 13.8, which is where this current assumption breaks down
See: https://docs.gitlab.com/ee/user/admin_area/settings/account_and_limit_settings.html#personal-access-token-prefix
=> fix(http): allow tokens to exceed 20 chars

src/GitLabApiClient/CommitsClient.cs, src/GitLabApiClient/ICommitsClient.cs, src/GitLabApiClient/Models/Commits/Requests/CreateCommitRequest/CreateCommitRequest.cs, src/GitLabApiClient/Models/Commits/Requests/CreateCommitRequest/CreateCommitRequestAction.cs, src/GitLabApiClient/Models/Commits/Requests/CreateCommitRequest/CreateCommitRequestActionEncoding.cs, src/GitLabApiClient/Models/Commits/Requests/CreateCommitRequest/CreateCommitRequestActionType.cs, test/GitLabApiClient.Test/CommitsClientMockedTest.cs, test/GitLabApiClient.Test/CommitsClientTest.cs, test/GitLabApiClient.Test/Utilities/GitLabApiHelper.cs
See https://docs.gitlab.com/ee/api/commits.html#create-a-commit-with-multiple-files-and-actions.
Renamed existing test class from CommitsClientTest to CommitsClientMockedTest as it worked with mocks.
For this new functionality I added Docker tests so it matches the pattern of the other tests.
Please let me know if anything else is needed. Thanks in advance!
=> Added create commit API
