nmklotas/GitLabApiClient

src/GitLabApiClient/GroupsClient.cs
src/GitLabApiClient/Internal/Http/GitLabHttpFacade.cs
src/GitLabApiClient/Internal/Http/GitlabApiRequestor.cs
src/GitLabApiClient/Internal/Queries/GroupsProjetsQueryBuilder.cs
src/GitLabApiClient/Internal/Queries/GroupsQueryBuilder.cs
src/GitLabApiClient/Internal/Queries/QueryBuilder.cs
src/GitLabApiClient/Internal/Utilities/Guard.cs
src/GitLabApiClient/Models/Groups/Requests/CreateGroupRequest.cs
src/GitLabApiClient/Models/Groups/Requests/GroupLdapLinkRequest.cs
src/GitLabApiClient/Models/Groups/Requests/GroupsOrder.cs
src/GitLabApiClient/Models/Groups/Requests/GroupsProjectsOrder.cs
src/GitLabApiClient/Models/Groups/Requests/GroupsProjectsQueryOptions.cs
src/GitLabApiClient/Models/Groups/Requests/GroupsQueryOptions.cs
src/GitLabApiClient/Models/Groups/Requests/GroupsSort.cs
src/GitLabApiClient/Models/Groups/Requests/GroupsVisibility.cs
src/GitLabApiClient/Models/Groups/Requests/UpdateGroupRequest.cs
src/GitLabApiClient/Models/Projects/Responses/Group.cs

groups api client

---

src/GitLabApiClient/ProjectsClient.cs

Typo: it's -> its.

---

src/GitLabApiClient/ProjectsClient.cs

Add support for archive and unarchive in ProjectsClient.

ProjectsClient: Add (un)archive methods

---

src/GitLabApiClient/MergeRequestsClient.cs

Fix issue #22

---

src/GitLabApiClient/GitLabClient.cs
src/GitLabApiClient/GroupsClient.cs
src/GitLabApiClient/Internal/Queries/GroupsQueryBuilder.cs
src/GitLabApiClient/IssuesClient.cs
src/GitLabApiClient/MergeRequestsClient.cs
src/GitLabApiClient/Models/AccessLevel.cs
src/GitLabApiClient/Models/Groups/Requests/AddGroupMemberRequest.cs
src/GitLabApiClient/Models/Groups/Requests/GroupsQueryOptions.cs
src/GitLabApiClient/Models/Groups/Requests/UpdateGroupMemberRequest.cs
src/GitLabApiClient/Models/Member.cs
src/GitLabApiClient/ProjectsClient.cs
src/GitLabApiClient/UsersClient.cs
test/GitLabApiClient.Test/GitLabClientTest.cs
test/GitLabApiClient.Test/Inspections/RequestsInspectionTest.cs

* Include WithCustomAttributes and MinAccessLevel to GroupsQueryOptions
* Support retrieving a group's subgroups
* Support retrieving and managing group membership

Updates to groups client

---

src/GitLabApiClient/GitLabApiClient.csproj

Support net45 as a second TargetFramework

Support net45

---

src/GitLabApiClient/Internal/Queries/ReleaseQueryBuilder.cs
src/GitLabApiClient/Internal/Queries/ReleasesQueryBuilder.cs
src/GitLabApiClient/Models/Releases/Requests/CreateReleaseRequest.cs
src/GitLabApiClient/Models/Releases/Requests/DeleteReleaseRequest.cs
src/GitLabApiClient/Models/Releases/Requests/ReleaseQueryOptions.cs
src/GitLabApiClient/Models/Releases/Requests/UpdateReleaseRequest.cs
src/GitLabApiClient/Models/Releases/Responses/Asset.cs
src/GitLabApiClient/Models/Releases/Responses/Commit.cs
src/GitLabApiClient/Models/Releases/Responses/Link.cs
src/GitLabApiClient/Models/Releases/Responses/Release.cs
src/GitLabApiClient/Models/Releases/Responses/Source.cs
src/GitLabApiClient/ReleaseClient.cs
test/GitLabApiClient.Test/ReleasesTest.cs
test/GitLabApiClient.Test/Utilities/GitLabApiHelper.cs

24 support release

---

src/GitLabApiClient/Models/Issues/Responses/Issue.cs
src/GitLabApiClient/Models/MergeRequests/Responses/MergeRequest.cs

Added ClosedBy and ClosedAt property to issues and merge-requests

---

src/GitLabApiClient/Internal/Queries/TagQueryBuilder.cs
src/GitLabApiClient/Models/Tags/Requests/CreateTagRequest.cs
src/GitLabApiClient/Models/Tags/Requests/DeleteTagRequest.cs
src/GitLabApiClient/Models/Tags/Requests/TagOrder.cs
src/GitLabApiClient/Models/Tags/Requests/TagQueryOptions.cs
src/GitLabApiClient/Models/Tags/Requests/TagQueryOptsions.cs
src/GitLabApiClient/Models/Tags/Requests/TagSort.cs
src/GitLabApiClient/Models/Tags/Responses/Tag.cs
src/GitLabApiClient/TagClient.cs

Enables support for the Gitlab Tags-API

Support for Tags

---

src/GitLabApiClient/MarkdownClient.cs
src/GitLabApiClient/Models/Markdown/Request/RenderMarkdownRequest.cs
src/GitLabApiClient/Models/Markdown/Response/Markdown.cs

Markdown Support

---

src/GitLabApiClient/GitLabClient.cs

Fixed missing properties in GitLabClient.cs

---

src/GitLabApiClient/Models/Issues/Responses/ClosedBy.cs
src/GitLabApiClient/Models/Issues/Responses/Issue.cs
src/GitLabApiClient/Models/MergeRequests/Responses/MergeRequest.cs

* Added new class `ClosedBy`
* Changed types for `ClosedBy` property from string to `ClosedBy` class
* Should fix #50

Fix JSON deserialization issue

---

src/GitLabApiClient/TagClient.cs

fix string interpolation inside tag client

---

src/GitLabApiClient/Internal/Queries/ProjectIssuesQueryBuilder.cs
src/GitLabApiClient/IssuesClient.cs
src/GitLabApiClient/Models/Issues/Requests/ProjectIssuesQueryOptions.cs
test/GitLabApiClient.Test/Internal/Queries/ProjectIssuesQueryBuilderTest.cs

https://docs.gitlab.com/ee/api/issues.html

fix Issues API, id is a path param not a query param

---

src/GitLabApiClient/Internal/Http/GitLabApiPagedRequestor.cs

Definitely not as performant as when total pages is available but it will still give back a listed result.
> ⚠️ Caution: For performance reasons since GitLab 11.8 and behind the api_kaminari_count_with_limit feature flag, if the number of resources is more than 10,000, the X-Total and X-Total-Pages headers as well as the rel="last" Link are not present in the response headers.
https://docs.gitlab.com/ee/api/#other-pagination-headers

support pagination when x-total-pages is not available

---

src/GitLabApiClient/GroupsClient.cs
src/GitLabApiClient/Internal/Queries/GroupsProjectsQueryBuilder.cs
src/GitLabApiClient/Models/Groups/Requests/ProjectsGroupQueryOptions.cs
test/GitLabApiClient.Test/Internal/Queries/ProjectsGroupsQueryBuilderTest.cs

https://docs.gitlab.com/ee/api/groups.html#list-a-groups-projects

fix group projects API query parameters

---

README.md

projectId paramter has been removed from CreateIssueRequest constructor

API doc update

---

src/GitLabApiClient/GitLabApiClient.csproj
src/GitLabApiClient/Internal/Queries/QueryBuilder.cs
src/GitLabApiClient/Internal/Utilities/Extensions.cs
src/GitLabApiClient/Models/Webhooks/Requests/CreateWebhookRequest.cs
test/GitLabApiClient.Test/Internal/GroupIdConversionTest.cs
test/GitLabApiClient.Test/Internal/ProjectIdConversionTest.cs
test/GitLabApiClient.Test/Internal/Queries/GroupsQueryBuilderTest.cs
test/GitLabApiClient.Test/Internal/Queries/IssuesQueryBuilderTest.cs
test/GitLabApiClient.Test/Internal/Queries/MergeRequestsQueryBuilderTest.cs
test/GitLabApiClient.Test/Internal/Queries/MilestonesQueryBuilderTest.cs
test/GitLabApiClient.Test/Internal/Queries/PipelineQueryBuilderTest.cs
test/GitLabApiClient.Test/Internal/Queries/ProjectIssuesQueryBuilderTest.cs
test/GitLabApiClient.Test/Internal/Queries/ProjectMergeRequestsQueryBuilderTest.cs

Use `Uri.EscapeDataString` even for query as GitLab there seems to handle all cases.

fix URL encoding

---

.github/workflows/ci.yml

should hopefully fix random failing with GitVersion lock file.

fix github ci

---

src/GitLabApiClient/Internal/Http/Serialization/JsonSerializer.cs

Fixes https://github.com/nmklotas/GitLabApiClient/issues/154

Fixed json default settings override

---

src/GitLabApiClient/Models/Notes/Responses/Note.cs
src/GitLabApiClient/Models/Notes/Responses/Position.cs
src/GitLabApiClient/Models/Notes/Responses/PositionType.cs

Added Resolved, ResolvedBy and Position properties to Note model.
Added PositionType enum.
Added Position model.

Extend Note model with Resolved, ResolvedBy and Position properties.

---

docker/init.rb
src/GitLabApiClient/GroupsClient.cs
src/GitLabApiClient/Models/Groups/Requests/AddGroupMemberRequest.cs
test/GitLabApiClient.Test/GroupsClientTest.cs
test/GitLabApiClient.Test/Utilities/GitLabApiHelper.cs

There was no userid field in the add group member so that could not have worked.

Add user to the group now actually works

---

src/GitLabApiClient/Models/MergeRequests/Responses/MergeRequestState.cs

With the recent changes from gitlab, seems like they added this value as possible.
Fixes #157

Add value for CannotBeMerged in Status

---

.github/workflows/drafter.yml
docker/init.rb
src/GitLabApiClient/IRunnersClient.cs
src/GitLabApiClient/Internal/Http/GitLabHttpFacade.cs
src/GitLabApiClient/Internal/Http/GitlabApiRequestor.cs
src/GitLabApiClient/Models/Runners/Requests/CreateRunnerRequest.cs
src/GitLabApiClient/Models/Runners/Requests/UpdateRunnerRequest.cs
src/GitLabApiClient/Models/Runners/Responses/RunnerDetails.cs
src/GitLabApiClient/Models/Runners/Responses/RunnerProject.cs
src/GitLabApiClient/Models/Runners/Responses/RunnerToken.cs
src/GitLabApiClient/RunnersClient.cs
test/GitLabApiClient.Test/GroupsClientTest.cs
test/GitLabApiClient.Test/ProjectsClientTest.cs
test/GitLabApiClient.Test/RunnersClientTest.cs
test/GitLabApiClient.Test/Utilities/GitLabApiHelper.cs
test/GitLabApiClient.Test/Utilities/GitLabContainerFixture.cs

Fixed some typos in the Runners client in the docs and fixed the Update method to actually update a Runner with Runner data and not User?! data

Update runners command

---

src/GitLabApiClient/GitLabApiClient.csproj

https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg#project-properties

add license expression

---

src/GitLabApiClient/GitLabApiClient.csproj

fix nuget health issue
